---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ziti.sixfeetup.com
  resources:
  - zitiidentities
  - zitiservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ziti.sixfeetup.com
  resources:
  - zitiidentities/finalizers
  - zitiservices/finalizers
  verbs:
  - update
- apiGroups:
  - ziti.sixfeetup.com
  resources:
  - zitiidentities/status
  - zitiservices/status
  verbs:
  - get
  - patch
  - update
