apiVersion: v1
kind: Secret
metadata:
  name: openziti-management
type: Opaque
stringData:
  controllerUrl: https://ziti.example.com/edge/management/v1
  username: admin
  password: change-me
  caBundle: |
    -----BEGIN CERTIFICATE-----
    change-me
    -----END CERTIFICATE-----
