apiVersion: ziti.sixfeetup.com/v1alpha1
kind: ZitiAccessPolicy
metadata:
  name: argocd-devops-dial
spec:
  type: Dial
  identitySelector:
    matchRoleAttributes:
    - devops
  serviceSelector:
    matchNames:
    - argocd
